//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KKHBed
    {
        public int Bednumber { get; set; }
        public string Patientnumber { get; set; }
        public string Doctornumber { get; set; }
        public string Nursenumber { get; set; }
        public string Therapistnumber { get; set; }
        public string Timein { get; set; }
        public string Timeout { get; set; }
    }
}
